### ISSUE TITLE
It is possible to make enum nullable?

### ISSUE THREAD

**Issue by paolooo** [spatie/laravel-enum#24]
MotivationEnums::make() expects string|int as argument but NULL given

**Comment by paolooo** [comment]
Thanks for the quick reply @Gummibeer. 

The column for this enum in my database is nullable.

**Comment by Gummibeer** [comment]
We could extend the `$enums` array by an optional `nullable` flag that indicates to return `null` if current value is `null` instead of trying to create an Enum instance.

```php
protected $enums = [
    'status' => TestModelStatus::class.':nullable',
];
```

**Comment by paolooo** [comment]
Yeah! That would be an elegant solution.

**Comment by Gummibeer** [comment]
Do you want to open a PR during hacktoberfest? Or should we do it internal?

**Comment by paolooo** [comment]
I'll try to add a PR.

I was thinking, to add NullObject too, so that we can still do the following:

```php
$model->enum->getIndex();   // returns null
```

But I'm not sure if it ENUM should support NULL. I saw a discussion here ( https://www.quora.com/Should-enum-be-nullable-or-not ). What do you think about it?

**Comment by Gummibeer** [comment]
For me it's a clear no. An Enum is a finite list of string names with an integer index. So `null` isn't part of it.

I'm ok with adding this nullable feature to the Laravel wrapper. But the nullable enum object should be changed in the Enum package itself and the idea of this package was a strong typed enum. Because @brendt and I prefer strong typing.

**Comment by brendt** [comment]
If I can pitch in. I'm in favour of adding nullable support, but I'm not sure adding it as a textual flag is the way to go. I recently released the model-states package, in which we decided to use a dedicated method to configure states, like so:

```php
class Payment extends Model
{
    use HasStates;

    protected function registerStates(): void
    {
        $this
            ->addState('state', PaymentState::class)
            ->allowTransition(Pending::class, Paid::class)
            ->allowTransition(Pending::class, Failed::class, PendingToFailed::class);
    }
}
```

This method adds more flexibility for future config options, and is — in my opinion — a cleaner solution. I suggest one of two things:

- Allow both the `registerEnums` method and `protected $enums` syntax as a shorthand
- Only use `registerEnums`, I personally prefer one well documented way to do something, rather than several. I realise this is not the Laravel mindset per se, so I'm also fine with option 1.

It's not like I'm 100% against @Gummibeer's proposal though, I just wanted to pitch in another idea.

**Comment by Gummibeer** [comment]
My idea was based on the already known rules or even the casts in Laravel. Only using the method would make it more complicated for all users without the need of nullable enums and also moves the enums away from the casts.

So I would still prefer the string flag in the array to stick with an already known system. Primary because it extends the casts and should be very similar to them.

**Comment by brendt** [comment]
Good point, I'm fine with it!

**Comment by paolooo** [comment]
Makes sense 👍 I'm ok with it, too.

**Comment by paolooo** [comment]
Quick question, why is it we are using `$enums` variable instead of `$casts`?

```php
protected $enums = [
    'status' => TestModelStatus::class.':nullable',
];
```

vs

```php
protected $casts = [
    'status' => TestModelStatus::class.':nullable',
];
```

**Comment by Gummibeer** [comment]
Because it's super hard to get into the normal casting logic. There are multiple issues in the Laravel core to make the cast logic extendable but until now nothing happened. And to keep conflicts with other packages low we decided to use a new property.

**Comment by paolooo** [comment]
Thanks.

**Comment by gaelreyrol** [comment]
Has the nullable feature been implemened ?

**Comment by freekmurze** [comment]
We'll continue this conversation in #25

**Comment by devamjad** [comment]
$table->enum('is_active', ['yes','no'])->after('column_name')->nullable();

The above is not a good approach but we can do it this way.

**Comment by syamsoul** [comment]
thank you for making this happen... i just try add the code below in my `Model` file, and it is working..

thanks

```
protected $casts = [
    'status' => MyStatusEnum::class.':nullable',
];
```
