### ISSUE TITLE
Hability to blacklist static methods

### ISSUE THREAD

**Issue by gjm** [spatie/laravel-enum#39]
I know this issue has been discussed in spatie/enum#28 but with the recent addition of the `Castable` interface in Laravel I believe this needs to be revised.

I've created custom casters to `Enum` classes and would like to be able to make them implement the `Castable` interface which required a `public static castUsing()` method.

Currently this is impossible with `Enum` classes because static methods are assumed to be enum values. An `@ignoreEnum` doc annotation, like suggested in the issue, would solve this while still maintaining backwards compatibility.

**Comment by Gummibeer** [comment]
Hey, I've transferred the issue to the laravel-enum package because your usecase applies to the Laravel implementation.
Because this specific usecase will be solved by #31 I still don't see the point to allow custom static methods on an enum class.
For this specific case we will check for the interface implementation and ignore the `castUsing()` method.

This will be done on a new `Enum` class in this laravel-enum package because it's an optional and Laravel specific case.

**Comment by gjm** [comment]
@Gummibeer OK, I'll be watching. Thanks.

**Comment by brendt** [comment]
Can I pitch in? I think `Castable` should be supported by this package, as soon as Laravel's new version is tagged. I wouldn't support a blacklist.

**Comment by gjm** [comment]
@brendt I agree. It's already available in [7.4.0](https://github.com/laravel/framework/tree/v7.4.0).

**Comment by brendt** [comment]
There's still a pending PR that would be needed for this to work: https://github.com/laravel/framework/pull/32213
