### ISSUE TITLE
Can't install with Enum package

### ISSUE THREAD

**Issue by asivaneswaran** [spatie/laravel-enum#50]
When I try to install this package along side the Spatie/Enum package, I get the following error:
```
  Problem 1
    - Installation request for spatie/enum (locked at 3.1.1, required as ^3.1) -> satisfiable by spatie/enum[3.1.1].
    - spatie/laravel-enum 1.6.0 requires spatie/enum ^2.3 -> satisfiable by spatie/enum[v2.x-dev].
    - spatie/laravel-enum 1.6.1 requires spatie/enum ^2.3 -> satisfiable by spatie/enum[v2.x-dev].
    - Conclusion: don't install spatie/enum v2.x-dev
    - Installation request for spatie/laravel-enum ^1.6 -> satisfiable by spatie/laravel-enum[1.6.0, 1.6.1].
```

**Comment by Gummibeer** [comment]
Hey,
yes - this package is a bit behind.
Because v3 of the base Enum package was a massive refactoring the v2 of this one is also bigger.
https://github.com/spatie/laravel-enum/pull/44
We would be happy to receive real-world feedback in the PR. You can install the `v2.x-dev` version and test it.
If everything is fine and we get feedback we will release it.
