### ISSUE TITLE
use Laravel Enum in combination with database migration (and: how to list possible values)

### ISSUE THREAD

**Issue by wivaku** [spatie/laravel-enum#82]
Two part question:
1. is it possible to create a collection of possible values for an enum? I see the Model $casts, but how would I achieve it outside a Model, e.g. in tinker?
2. how do I use Laravel Enum in combination with a database migration?

This to avoid hardcoding e.g.
```
            $table->enum('status', ['draft','approved','archived']);
```

Could be I am misunderstanding the package, in which case: apologies!

**Comment by wivaku** [comment]
Thanks, exactly what I was looking for! I checked the documentation, but did not think of checking the source code.  
And yes, good point about the drawbacks of a DB enum. I will pick string / integer instead.  
But still useful to know about the static methods.

**Comment by wivaku** [comment]
Don't think it's documented in the base package. Creating a PR is a bridge too far for me at the moment I'm afraid, sorry. 

Related, for integer values, I assume I always have to [specify them explicitly](https://github.com/spatie/enum#enum-values)? I.e. there's no implicit way to get integer values for a Enum if there's no `function values()` defined?

**Comment by Gummibeer** [comment]
You are right - we had this in v2 I think but it comes with the problem that the order of your doc-tags is super important as reordering them will result in a totally different mapping.
That's why we decided for the explicit one.


Regarding the PR: 
You go to create a new file at [docs/usage/6-list-enum-values.md](https://github.com/spatie/enum/new/master?filename=docs/usage/6-list-enum-values.md) and copy the whole content of [docs/usage/5-comparing-enums.md](https://github.com/spatie/enum/edit/master/docs/usage/5-comparing-enums.md) for example.

Then you adjust this first block surrounded by dashes to
```md
---
title: List Enum Values
weight: 6
---
```

After that you replace everything else in the file with the new parts - so short examples for `cases()`, `toArray()`, `toValues()` and `toLabels()`.

If you are done you click on the green `propose new file` button. After that you should get redirected to the diff view and can create a PR.

Looking forward to your PR! 🥳
