### ISSUE TITLE
Not nullable enums break Laravel Nova create resource

### ISSUE THREAD

**Issue by HakimBe** [spatie/laravel-enum#90]
Hello,

first of all, i will explain the situation:
i have an eloquent model that has not nullable enum fields.
This model has a Laravel nova resource related to it.
am having the NotNullableEnumField exception thrown when i try to create a new model instance via Laravel nova.

**There is my cast on the eloquent model:**
```
protected $casts = [
    'status' => ModelStatusEnum::class,
    'type' => ModelTypeEnum::class,
];
```

**There is the related Laravel nova fields**
```
Select::make('Type')
      ->options(ModelTypeEnum::toArray())
      ->rules('required', new EnumRule(ModelTypeEnum::class))
      ->displayUsingLabels(),

Select::make('Status')
    ->options(ModelStatusEnum::toArray())
    ->rules('required', new EnumRule(ModelStatusEnum::class))
    ->displayUsingLabels(),
```

**There is the exception thrown on creating a new instance:**
Spatie\\Enum\\Laravel\\Exceptions\\NotNullableEnumField(code: 0): Field type on model ... is not nullable

**this is my setup:**
php: 8.0.1
spatie/laravel-enum: 2.5.2
Laravel: 8.78.1
Laravel nova: 3.30

Thank you in advance.

**Comment by Gummibeer** [comment]
Hey,
I know about it but except of making the field nullable I don't know/see any solution.

**Comment by Synchro** [comment]
I've just run into this one again. I [reported it in Nova last year](https://github.com/laravel/nova-issues/issues/3456), but it as closed as a Spatie issue. Something that's not mentioned here is that if it's not nullable it should have a default value, but sadly adding a `default()` call in the Nova field doesn't help.

Perhaps it's enforcing the lack of nullability in a `make` call rather than later on when it's added to the DB, and nova creates a placeholder resource that runs not this limit when when populating its create form?

I'm guessing that this repo may not be receiving much Spatie love now that PHP 8.1 has native enums, but I'm stuck on 8.0 for now.
